name: 2 - Process Policies

on:
  workflow_dispatch:
    inputs:
      az_powershell_min_version:
        required: true
        type: string
      Ewoks_MG_Resource_Id:
        required: true
        type: string

jobs:
  deploy-policy-definitions-and-assignments:
    runs-on: [self-hosted, linux]

    env:
      az_powershell_min_version: ${{ inputs.az_powershell_min_version }}
      # why set these 2 env vars?  They are not used in this workflow
      top_management_resource_group_id: ${{ inputs.Ewoks_MG_Resource_Id }}
    
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        name: Azure OIDC login
        with:         
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true
      
      - uses: azure/arm-deploy@v1 
        name: Deploy custom policy definitions
        id: customPolicyDefinitions
        with:
          scope: managementgroup
          region: westeurope
          managementgroupid: ${{ inputs.Ewoks_MG_Resource_Id }}
          template: ./modules/policies/definitions/customPolicyDefinitions.bicep
          parameters: >
            ./modules/policies/definitions/parameters/customPolicyDefinitions.parameters.all.json
            parTargetManagementGroupId="${{ inputs.Ewoks_MG_Resource_Id }}"