name: MGs Diagnostic Settings Orchestration

on:
  workflow_dispatch:
    inputs:
      Ewoks_MG_Resource_Id:
        required: true
        type: string

jobs:
  deploy-central-logging:
    runs-on: [self-hosted, linux]
    
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v1
        name: Azure OIDC login
        with:         
          tenant-id: ${{ secrets.TENANT_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - uses: azure/arm-deploy@v1
        name: Deploy Management Groups Diagnostic Settings
        id: deployMGsDiagSettings
        with:
          scope: managementGroup
          region: westeurope
          managementgroupid: ${{ inputs.Ewoks_MG_Resource_Id }}
          subscriptionId: ${{ inputs.Subscription_Id }}
          template: ./orchestration/mgDiagSettingsAll/mgDiagSettingsAll.bicep
          parameters: ./orchestration/mgDiagSettingsAll/parameters/bicepconfig.json